### ISSUE TITLE
The right hand operand should be a single expression?

### ISSUE THREAD

**Issue by armeniomiranda** [hemanth/haz-touch#10]
I think the condition should be:
```js
'DocumentTouch' in window && (document instanceof DocumentTouch || 'ontouchstart' in window || navigator.maxTouchPoints > 0 || navigator.msMaxTouchPoints > 0)
```
since,
```js
false && true  || true      // returns true
false && (true || true)     // returns false
```

**Comment by hemanth** [comment]
There wouldn't be cases when those conditions would occur?

**Comment by armeniomiranda** [comment]
I understood what you're doing, if ```'DocumentTouch' in window``` is ```true```,  ```document instanceof DocumentTouch```should also be ```true```. It is correct, thanks.
